var $ = require('jquery');
var async = require('async');

module.exports.setProgress = function (progress) {
    $("#loader .progress-bar span").css('width',progress+'%');
};


var filesList = [
    'files/maps/textures/tree/1.png',
    'files/maps/textures/tree/2.png',
    'files/maps/textures/tree/3.png',
    'files/maps/textures/tree/4.png',
    'files/maps/textures/tree/5.png',
    'files/maps/textures/tree/6.png',
    'files/maps/textures/tree/7.png',
    'files/maps/textures/0.png',
    'files/maps/textures/0_snowy.png',
    'files/maps/textures/1.png',
    'files/maps/textures/2.png',
    'files/maps/textures/3.png',
    'files/maps/textures/11.png',
    'files/maps/textures/12.png',
    'files/maps/textures/13.png',
    'files/maps/textures/14.png',
    'files/maps/textures/33.png',
    'files/maps/textures/33a.png',
    'files/maps/textures/44.png',
    'files/maps/textures/45.png',
    'files/maps/textures/46.png',
    'files/maps/textures/66.png',
    'files/maps/textures/132.png',
    'files/maps/textures/156.png',
    'files/maps/textures/225.png',
    'files/maps/textures/264.png',
    'files/maps/textures/265.png',
    'files/maps/textures/266.png',
    'files/maps/textures/267.png',
    'files/maps/textures/268.png',
    'files/maps/textures/272.png',
    'files/maps/textures/273.png',
    'files/maps/textures/274.png',
    'files/maps/textures/280.png',
    'files/maps/textures/297.png',
    'files/maps/textures/298.png',
    'files/maps/textures/299.png',
    'files/maps/textures/300.png',
    'files/maps/textures/301.png',
    'files/maps/textures/305.png',
    'files/maps/textures/306.png',
    'files/maps/textures/307.png',
    'files/maps/textures/308.png',
    'files/maps/textures/309.png',
    'files/maps/textures/310.png',
    'files/maps/textures/313.png',
    'files/maps/textures/660.png',
    'files/maps/textures/661.png',
    'files/maps/textures/662.png',
    'files/maps/textures/693.png',
    'files/maps/textures/694.png',
    'files/maps/textures/695.png',
    'files/maps/textures/qb_hidden.png',
    'files/char/luigi.png',
    'files/char/luigi-duck.png',
    'files/char/luigi-jump.png',
    'files/char/luigi-run1.png',
    'files/char/luigi-run2.png',
    'files/char/luigi-run3.png',
    'files/char/luigi-skid.png',
    'files/char/luigi-throw.png',
    'files/char/luigi-throw-run1.png',
    'files/char/luigi-throw-run2.png',
    'files/char/luigi-throw-run3.png',
    'files/char/luigi-throw-skid.png',
    'files/char/mario.png',
    'files/char/mario-dead.png',
    'files/char/mario-jump.png',
    'files/char/mario-run1.png',
    'files/char/mario-run2.png',
    'files/char/mario-run3.png',
    'files/char/mario-skid.png',
    'files/char/super-mario.png',
    'files/char/super-mario-duck.png',
    'files/char/super-mario-jump.png',
    'files/char/super-mario-run1.png',
    'files/char/super-mario-run2.png',
    'files/char/super-mario-run3.png',
    'files/char/super-mario-skid.png',
    'files/char/colored/black_duck.png',
    'files/char/colored/black_jump.png',
    'files/char/colored/black_run1.png',
    'files/char/colored/black_run2.png',
    'files/char/colored/black_run3.png',
    'files/char/colored/black_skid.png',
    'files/char/colored/black_stand.png',
    'files/char/colored/black_throw.png',
    'files/char/colored/black_throw_run1.png',
    'files/char/colored/black_throw_run2.png',
    'files/char/colored/black_throw_run3.png',
    'files/char/colored/black_throw_skid.png',
    'files/char/colored/green_duck.png',
    'files/char/colored/green_jump.png',
    'files/char/colored/green_run1.png',
    'files/char/colored/green_run2.png',
    'files/char/colored/green_run3.png',
    'files/char/colored/green_skid.png',
    'files/char/colored/green_stand.png',
    'files/char/colored/green_throw.png',
    'files/char/colored/green_throw_run1.png',
    'files/char/colored/green_throw_run2.png',
    'files/char/colored/green_throw_run3.png',
    'files/char/colored/green_throw_skid.png',
    'files/char/colored/red_duck.png',
    'files/char/colored/red_jump.png',
    'files/char/colored/red_run1.png',
    'files/char/colored/red_run2.png',
    'files/char/colored/red_run3.png',
    'files/char/colored/red_skid.png',
    'files/char/colored/red_stand.png',
    'files/char/colored/red_throw.png',
    'files/char/colored/red_throw_run1.png',
    'files/char/colored/red_throw_run2.png',
    'files/char/colored/red_throw_run3.png',
    'files/char/colored/red_throw_skid.png',
    'files/char/colored/small_black_jump.png',
    'files/char/colored/small_black_run1.png',
    'files/char/colored/small_black_run2.png',
    'files/char/colored/small_black_run3.png',
    'files/char/colored/small_black_skid.png',
    'files/char/colored/small_black_stand.png',
    'files/char/colored/small_green_jump.png',
    'files/char/colored/small_green_run1.png',
    'files/char/colored/small_green_run2.png',
    'files/char/colored/small_green_run3.png',
    'files/char/colored/small_green_skid.png',
    'files/char/colored/small_green_stand.png',
    'files/char/colored/small_red_jump.png',
    'files/char/colored/small_red_run1.png',
    'files/char/colored/small_red_run2.png',
    'files/char/colored/small_red_run3.png',
    'files/char/colored/small_red_skid.png',
    'files/char/colored/small_red_stand.png',
    'files/breakable_wall/particle1.png',
    'files/breakable_wall/particle2.png',
    'files/breakable_wall/post_break.png',
    'files/bullet/bullet1.png',
    'files/bullet/bullet2.png',
    'files/bullet/bullet3.png',
    'files/bullet/bullet4.png',
    'files/bullet/bullet-blow1.png',
    'files/bullet/bullet-blow2.png',
    'files/bullet/bullet-blow3.png',
    'files/enemies/enemy_1-1.png',
    'files/enemies/enemy_1-2.png',
    'files/enemies/enemy_1-3.png',
    'files/enemies/enemy_2-1.png',
    'files/enemies/enemy_2-2.png',
    'files/enemies/enemy_2-3.png',
    'files/enemies/enemy_2-4.png',
    'files/img/coin.gif',
    'files/img/keyboard.png',
    'files/img/mario.png',
    'files/question_block/1.png',
    'files/question_block/2.png',
    'files/question_block/3.png',
    'files/question_block/4.png',
    'files/question_block/coin1.png',
    'files/question_block/coin2.png',
    'files/question_block/coin3.png',
    'files/question_block/coin4.png',
    'files/question_block/flower1.png',
    'files/question_block/flower2.png',
    'files/question_block/flower3.png',
    'files/question_block/flower4.png',
    'files/question_block/level-up.png',
    'files/question_block/mushroom.png',
    'files/question_block/qbb.png',
    'files/question_block/star1.png',
    'files/question_block/star2.png',
    'files/question_block/star3.png',
    'files/question_block/star4.png',
    'files/sounds/1up.wav',
    'files/sounds/Beep.wav',
    'files/sounds/Big Jump.wav',
    'files/sounds/Bowser Die.wav',
    'files/sounds/Break.wav',
    'files/sounds/Bump.wav',
    'files/sounds/Coin.wav',
    'files/sounds/Die.wav',
    'files/sounds/Enemy Fire.wav',
    'files/sounds/Fire Ball.wav',
    'files/sounds/Flagpole.wav',
    'files/sounds/Game Over.wav',
    'files/sounds/Item.wav',
    'files/sounds/Jump.wav',
    'files/sounds/Kick.wav',
    'files/sounds/Pause.wav',
    'files/sounds/Powerup.wav',
    'files/sounds/Skid.wav',
    'files/sounds/smb_level_complete.wav',
    'files/sounds/Squish.wav',
    'files/sounds/Thwomp.wav',
    'files/sounds/Vine.wav',
    'files/sounds/Warp.wav'
];

module.exports.loadFiles = function(cb) {
    var _self = this;

    var filesProcessed = 0;

    async.eachLimit(filesList, 10, function(fileUrl, cb) {
        $.get(fileUrl, function() {
            filesProcessed++;
            _self.setProgress(Math.floor((filesProcessed/filesList.length)*100*((100-10)/100))+10);
            cb();
        });
    }, cb);
};